version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

  app:
    build: ./node
    depends_on:
      - db
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
